spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    change-log: dev
  web:
    resources:
      static-locations: classpath:static/,file:./uploads/
app:
  storage:
    location: ./uploads/