spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieClub
    username: root
    password: admin
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:C:\Users\FELGEO31\IdeaProjects\SpringProject\uploads
app:
  storage:
    location: C:\Users\FELGEO31\IdeaProjects\SpringProject\uploads